[package]
name = "moss_kernel"
version = "0.1.0"
authors = ["7thFox <dev7thFox@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"